// ミッションのJST期間更新、達成判定、ギフト報酬互換性を本番ソースから検証する。
const fs = require('fs');
const vm = require('vm');
const path = require('path');
const source = fs.readFileSync(path.join(__dirname,'..','monster-hero','src','game-system.jsx'),'utf8');
const start = source.indexOf('const LOGIN_BONUS_REWARDS');
const end = source.indexOf('const STAT_POINT_GAIN');
const context = {};
vm.createContext(context);
vm.runInContext(`${source.slice(start,end)}\nglobalThis.__m={MISSION_DEFS,missionDailyPeriod,missionWeeklyPeriod,normalizeMissions,missionValue,missionClaimableCount,missionNextReset,buildGiftClaim};`,context);
const m=context.__m;
let failed=0;
const check=(name,ok)=>{console.log(`${ok?'OK':'NG'}: ${name}`);if(!ok)failed++;};
const at=s=>Date.parse(s);
check('デイリーはJST 04:00で切り替わる',m.missionDailyPeriod(at('2026-07-29T18:59:59Z'))==='2026-07-29'&&m.missionDailyPeriod(at('2026-07-29T19:00:00Z'))==='2026-07-30');
check('ウィークリーは月曜JST 04:00で切り替わる',m.missionWeeklyPeriod(at('2026-08-02T18:59:59Z'))==='2026-07-27'&&m.missionWeeklyPeriod(at('2026-08-02T19:00:00Z'))==='2026-08-03');
let state=m.normalizeMissions(null,at('2026-07-29T20:00:00Z'));state.daily={...state.daily,login:1,battles:3,wins:5,enhances:1};
check('通常デイリー4個達成でコンプリート',m.missionValue(state,'daily',m.MISSION_DEFS.daily[4])===4);
state.weekly={...state.weekly,battles:20,wins:50,enhances:10,dailyClaims:15,marketTrades:3,donations:3};state.weeklyLoginDays=['a','b','c','d','e'];
check('通常ウィークリー7個中6個でコンプリート',m.missionValue(state,'weekly',m.MISSION_DEFS.weekly[7])===7&&m.missionValue({...state,weekly:{...state.weekly,donations:0}},'weekly',m.MISSION_DEFS.weekly[7])===6);
state.sentDaily=m.MISSION_DEFS.daily.map(x=>x.id);state.sentWeekly=m.MISSION_DEFS.weekly.map(x=>x.id);
check('ギフト送付済みは未受取バッジに含めない',m.missionClaimableCount(state)===0);
const base={gold:0,breederPoints:0,ownedItems:{}};
const gift={rewards:[{type:'trainingTicket',amount:3},{type:'trainingTicketLarge',amount:2}],expiresAt:new Date(Date.now()+100000).toISOString(),claimedAt:null};
const claim=m.buildGiftClaim(gift,base);
check('トレーニング・修行チケットを既存IDへ加算',claim.ok&&claim.balances.ownedItems.training_ticket===3&&claim.balances.ownedItems.training_ticket_l===2);
const invalid=m.buildGiftClaim({...gift,rewards:[{type:'diamond',amount:1},{type:'unknown',amount:1}]},base);
check('不明報酬を含むギフトは全体を拒否',!invalid.ok&&base.gold===0);
check('ミッション画面はHOME BGMを継続',/MISSIONS:\s*'home'/.test(source));
check('固定ギフトIDと同期ロックで重複送付を防止',/gift_mission_\$\{type\}_\$\{period\}_\$\{mission\.id\}/.test(source)&&/missionClaimingRef\.current/.test(source));
process.exit(failed?1:0);
