// HOME放牧設定の0体・1体・5体保存、互換初期化、表示ライフサイクルを検証する。
const fs = require('fs');
const vm = require('vm');
const path = require('path');
const source = fs.readFileSync(path.join(__dirname, '..', 'monster-hero', 'src', 'game-system.jsx'), 'utf8');
const prefix = source.slice(0, source.indexOf('// =====================================================================\n// AUDIO:'));
const context = { React: { createElement:()=>null, useState(){}, useEffect(){}, useCallback(){}, useMemo(){}, useRef(){} } };
vm.createContext(context);
vm.runInContext(`${prefix}\nglobalThis.__pasture={normalizeHomePastureIds};`, context);
const { normalizeHomePastureIds } = context.__pasture;
let failed=0;
const check=(name,ok)=>{console.log(`${ok?'OK':'NG'}: ${name}`);if(!ok)failed++;};
const owned=Array.from({length:7},(_,i)=>({id:`m${i+1}`,baseId:i===6?'missing':'Mocchi'}));
const valid=new Set(['Mocchi']);
check('0体を保存できる', normalizeHomePastureIds([],owned,valid).length===0);
check('旧セーブは現在の1体表示で初期化する', JSON.stringify(normalizeHomePastureIds(null,owned,valid))===JSON.stringify(['m1']));
check('5体を保存し6体目は除外する', JSON.stringify(normalizeHomePastureIds(['m1','m2','m3','m4','m5','m6'],owned,valid))===JSON.stringify(['m1','m2','m3','m4','m5']));
check('重複・未所持・不明な種を除外する', JSON.stringify(normalizeHomePastureIds(['m1','m1','gone','m7'],owned,valid))===JSON.stringify(['m1']));
check('HOMEだけで歩行コンポーネントを生成する', /gameState==='HOME'[\s\S]*homePastureMasumons\.map\([\s\S]*HomeWalkingMasumon/.test(source));
check('画面離脱と非表示でタイマーを破棄する', /return \(\) => \{ mountedRef\.current = false; clearMotionTimer\(\); document\.removeEventListener\('visibilitychange'/.test(source));
check('保存キーと選択上限を実装する', source.includes("storeSet('mh_home_pasture_ids',next,false)") && /prev\.length>=5 \? prev/.test(source));
check('個体の下位置をz-indexへ反映する', source.includes('zIndex:Math.round(motion.y)'));
check('M/B管理で放牧設定をモンスター編成の後に表示する', source.indexOf('>モンスター編成</button>') < source.indexOf('onClick={openPastureSettings}'));
check('選択中の最大5体を上部から解除できる', source.includes('aria-label="選択中の放牧マスモン"') && source.includes('Array.from({length:5}') && source.includes('を放牧から外す'));
check('放牧一覧で共通の並べ替え・表示設定・詳細を使う', /gameState==='PASTURE_SETTINGS'[\s\S]*renderMonsterSortFilterBar\(\{singleType:true\}\)[\s\S]*monsterEntryMatchesDisplayFlags[\s\S]*setMasuMonDetail/.test(source));
check('転生星を画像下中央へ共通配置する', source.includes('.mh-rebirth-stars-overlay{position:absolute;left:0;right:0;bottom:1px}') && !source.includes('className="absolute -top-1 inset-x-0"'));
process.exit(failed?1:0);
